CREATE TABLE IF NOT EXISTS public.headshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
  uri TEXT NOT NULL,
  metadata JSONB
);

ALTER TABLE public.headshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users on headshots" ON public.headshots;
CREATE POLICY "Enable read access for authenticated users on headshots"
ON public.headshots
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable insert for service role on headshots" ON public.headshots;
CREATE POLICY "Enable insert for service role on headshots"
ON public.headshots
FOR INSERT
TO service_role
WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for service role on headshots" ON public.headshots;
CREATE POLICY "Enable update for service role on headshots"
ON public.headshots
FOR UPDATE
TO service_role
USING (true)
WITH CHECK (true);

GRANT ALL ON TABLE public.headshots TO anon;
GRANT ALL ON TABLE public.headshots TO authenticated;
GRANT ALL ON TABLE public.headshots TO service_role;

