CREATE TABLE IF NOT EXISTS public.pipeline_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  event_type TEXT NOT NULL,
  request_id TEXT,
  message TEXT,
  payload JSONB
);

ALTER TABLE public.pipeline_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users on pipeline_events" ON public.pipeline_events;
CREATE POLICY "Enable read access for authenticated users on pipeline_events"
ON public.pipeline_events
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Enable insert for service role on pipeline_events" ON public.pipeline_events;
CREATE POLICY "Enable insert for service role on pipeline_events"
ON public.pipeline_events
FOR INSERT
TO service_role
WITH CHECK (true);

GRANT ALL ON TABLE public.pipeline_events TO anon;
GRANT ALL ON TABLE public.pipeline_events TO authenticated;
GRANT ALL ON TABLE public.pipeline_events TO service_role;

